version: "1.0"
services:
  mongo-db:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
  springboot-build-app:
    image: springboot-build-app:1.0
    container_name: springboot-build-app
    ports:
      - "8080:8080"
    links:
      - mongo-db